version: "3"

# テンプレート開発用の設定です。
#
# 使い方:
# docker compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.template.yml up -d
#
# テンプレートを切り替える場合は ECCUBE_TEMPLATE_CODE を変更して docker compose restart を実行してください。

services:
  ec-cube:
    environment:
      # 使用するテンプレートコードを指定します。
      # 変更後は docker compose restart が必要です。
      ECCUBE_TEMPLATE_CODE: "${ECCUBE_TEMPLATE_CODE:-default}"
    volumes:
      - "./app/template:/var/www/html/app/template"
      - "./html/template:/var/www/html/html/template"
      - "./html/user_data:/var/www/html/html/user_data"
