#!/bin/sh
set -e

if [ ! -d /var/www/html/vendor/bin ]; then
    composer install \
        --no-scripts \
        --no-autoloader \
        --no-plugins \
        -d ${APACHE_DOCUMENT_ROOT}
    composer dumpautoload -o --apcu
fi

bin/console doctrine:query:sql 'select * from dtb_base_info' > /dev/null 2>&1 || (
    if [ -z ${DATABASE_URL} ]; then
        cp .env.dist .env
    fi
    composer run-script installer-scripts
    composer run-script auto-scripts
)

# chown/chmod を .git 以外に限定
find ${APACHE_DOCUMENT_ROOT} \( -path ${APACHE_DOCUMENT_ROOT}/vendor -prune \) -or \( -path ${APACHE_DOCUMENT_ROOT}/.git -prune \) -or -print0 \
  | xargs -0 chown www-data:www-data 2>/dev/null || true
find ${APACHE_DOCUMENT_ROOT} \( -path ${APACHE_DOCUMENT_ROOT}/vendor -prune \) -or \( -path ${APACHE_DOCUMENT_ROOT}/.git -prune \) -or \( -type d -print0 \) \
  | xargs -0 chmod g+s 2>/dev/null || true

echo "PassEnv APP_ENV APP_DEBUG TRUSTED_PROXIES TRUSTED_HOSTS" > /etc/apache2/conf-enabled/eccube_env.conf

if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
